/**
 * The contract between the viewer's global search panel and the main-process search.
 *
 * Kept in its own module rather than in `index.d.ts` because the panel imports these as values'
 * types alongside the defaults below, and because the main-process engine will import the same file
 * - one definition, not two that drift.
 */

/** What a search looks inside. `rigidModel` is off by default: it reads whole model payloads. */
export interface GlobalSearchKinds {
  db: boolean;
  loc: boolean;
  text: boolean;
  rigidModel: boolean;
}

/**
 * Where a search looks.
 *
 * The three set-valued sources are resolved main-side rather than sent as pack lists: the viewer
 * window holds no mod list of its own (`rendererViewer.ts` never dispatches one), and `appData`
 * already knows which packs are open, enabled and installed.
 */
export type GlobalSearchSource =
  | { kind: "vanilla" }
  | { kind: "openPacks" }
  | { kind: "enabledMods" }
  | { kind: "allMods" }
  /** One specific pack, for the per-open-pack checkboxes. */
  | { kind: "pack"; path: string };

export interface GlobalSearchRequest {
  /** Generated by the panel and echoed back on every message, so a stale run can be ignored. */
  searchId: string;
  query: string;
  caseSensitive: boolean;
  regex: boolean;
  kinds: GlobalSearchKinds;
  sources: GlobalSearchSource[];
  /** Which half of a loc entry to match. Defaults to both. */
  locSearchIn?: "keys" | "values" | "both";
  maxResults?: number;
  maxResultsPerTarget?: number;
  maxResultsPerFile?: number;
  maxFileBytes?: number;
}

interface GlobalSearchResultBase {
  packPath: string;
  /** Human name where there is one, else the pack file name. */
  packLabel: string;
}

/**
 * A superset of `DBTableSelection`, so the panel can hand it to `handleOpenDBTable` unchanged.
 * `rowIndex` and `columnName` are for scrolling to and highlighting the cell once the table opens.
 */
export interface GlobalSearchDbResult extends GlobalSearchResultBase {
  kind: "db";
  packedFilePath: string;
  dbName: string;
  dbSubname: string;
  dbFolder?: string;
  columnName: string;
  rowIndex: number;
  value: string;
  matchStart: number;
  matchEnd: number;
}

export interface GlobalSearchLocResult extends GlobalSearchResultBase {
  kind: "loc";
  filePath: string;
  key: string;
  value: string;
  matchedIn: "key" | "value";
  matchStart: number;
  matchEnd: number;
}

export interface GlobalSearchTextResult extends GlobalSearchResultBase {
  kind: "text";
  filePath: string;
  /** 1-based, as an editor shows it. */
  line: number;
  column: number;
  offset: number;
  excerpt: string;
  matchStartInExcerpt: number;
  matchEndInExcerpt: number;
}

/** No line number: a model is binary, so a byte offset is the only honest position. */
export interface GlobalSearchRigidModelResult extends GlobalSearchResultBase {
  kind: "rigidModel";
  filePath: string;
  offset: number;
  encoding: "utf8" | "utf16le";
  excerpt: string;
  matchStartInExcerpt: number;
  matchEndInExcerpt: number;
}

export type GlobalSearchResult =
  GlobalSearchDbResult | GlobalSearchLocResult | GlobalSearchTextResult | GlobalSearchRigidModelResult;

export type GlobalSearchResultKind = GlobalSearchResult["kind"];

/** Streamed while a search runs, so the tree fills in rather than appearing at the end. */
export interface GlobalSearchResultBatch {
  searchId: string;
  results: GlobalSearchResult[];
}

export interface GlobalSearchProgress {
  searchId: string;
  stage: "planning" | "vanillaDb" | "vanillaLoc" | "pack" | "done";
  targetsDone: number;
  targetsTotal: number;
  /** Within the current target. `filesTotal` is unknown until its index has been read. */
  filesScanned: number;
  filesTotal?: number;
  currentLabel?: string;
  resultCount: number;
  elapsedMs: number;
}

export interface GlobalSearchSkippedFile {
  packPath: string;
  filePath: string;
  reason: "tooLarge" | "unreadable";
}

export interface GlobalSearchResponse {
  success: boolean;
  searchId: string;
  canceled: boolean;
  truncated: boolean;
  results: GlobalSearchResult[];
  counts: Record<GlobalSearchResultKind, number>;
  targetsSearched: number;
  filesScanned: number;
  skippedFiles: GlobalSearchSkippedFile[];
  /** Coverage caveats worth showing, e.g. "base game DB: text columns only". */
  warnings: string[];
  elapsedMs: number;
  error?: string;
}

export const DEFAULT_GLOBAL_SEARCH_KINDS: GlobalSearchKinds = {
  db: true,
  loc: true,
  text: true,
  rigidModel: false,
};

/** Long enough for any real query, short enough that a pasted file cannot become a pattern. */
export const MAX_GLOBAL_SEARCH_QUERY_LENGTH = 512;

export const GLOBAL_SEARCH_RESULT_KINDS: GlobalSearchResultKind[] = ["db", "loc", "text", "rigidModel"];

/** The file a result lives in, for grouping and for opening it. DB results name their table file. */
export const getGlobalSearchResultFilePath = (result: GlobalSearchResult): string =>
  result.kind === "db" ? result.packedFilePath : result.filePath;
